const { PrismaClient } = require("@prisma/client")
const prisma = new PrismaClient()

const topics = [
  // ─────── FRONTEND ───────
  {
    slug: "html",
    title: "HTML",
    description: "The foundation of every web page — structure, semantics, and accessibility.",
    category: "FRONTEND",
    icon: "Code2",
    order: 1,
    difficulty: "BEGINNER",
    questions: [
      {
        questionText: "Which HTML5 element is used to define the main navigation links?",
        options: ["<navigation>", "<nav>", "<menu>", "<links>"],
        correctAnswer: 1,
        explanation: "The <nav> element is a semantic HTML5 element specifically designed to define a set of navigation links.",
        order: 1,
      },
      {
        questionText: "What does DOCTYPE declaration do?",
        options: ["Defines CSS styles", "Tells the browser which HTML version to use", "Imports JavaScript", "Creates a document title"],
        correctAnswer: 1,
        explanation: "<!DOCTYPE html> tells the browser to render the page in standards mode using HTML5, preventing quirks mode rendering.",
        order: 2,
      },
      {
        questionText: "Which attribute makes a form input required before submission?",
        options: ["mandatory", "validate", "required", "must"],
        correctAnswer: 2,
        explanation: "The 'required' attribute on form inputs prevents form submission if the field is empty and shows a browser validation message.",
        order: 3,
      },
      {
        questionText: "What is the correct semantic element for the most important heading?",
        options: ["<header>", "<h1>", "<title>", "<heading>"],
        correctAnswer: 1,
        explanation: "<h1> is the highest-level heading in HTML. There should typically be only one <h1> per page, representing the main topic.",
        order: 4,
      },
      {
        questionText: "Which HTML element is used to embed an image?",
        options: ["<picture>", "<image>", "<img>", "<src>"],
        correctAnswer: 2,
        explanation: "<img> is the correct element. It's a void element (no closing tag) and requires a src attribute and ideally an alt attribute for accessibility.",
        order: 5,
      },
      {
        questionText: "What is the purpose of the 'alt' attribute on <img>?",
        options: ["Sets the image title tooltip", "Provides alternative text for screen readers and when image fails", "Specifies the image format", "Defines image dimensions"],
        correctAnswer: 1,
        explanation: "The alt attribute provides alternative text for users with screen readers and is displayed when an image fails to load. It's critical for accessibility.",
        order: 6,
      },
      {
        questionText: "Which element should wrap the page's primary content, excluding headers/navs/footers?",
        options: ["<content>", "<div>", "<main>", "<body>"],
        correctAnswer: 2,
        explanation: "<main> is a semantic landmark element that contains the primary content of the document. There should only be one <main> per page.",
        order: 7,
      },
    ],
  },
  {
    slug: "css",
    title: "CSS",
    description: "Style, layout, and responsive design — from Flexbox to Grid to animations.",
    category: "FRONTEND",
    icon: "Paintbrush",
    order: 2,
    difficulty: "BEGINNER",
    questions: [
      {
        questionText: "In the CSS box model, which property creates space OUTSIDE the border?",
        options: ["padding", "margin", "spacing", "gap"],
        correctAnswer: 1,
        explanation: "Margin creates space outside the element's border, pushing it away from neighboring elements. Padding creates space inside the border.",
        order: 1,
      },
      {
        questionText: "Which CSS property is used to make a Flexbox container?",
        options: ["display: flexbox", "display: flex", "flex: true", "layout: flex"],
        correctAnswer: 1,
        explanation: "display: flex turns an element into a flex container, enabling flex properties on its direct children.",
        order: 2,
      },
      {
        questionText: "What does 'justify-content: space-between' do in Flexbox?",
        options: ["Centers items vertically", "Adds equal space between and around all items", "Distributes items with equal space between them, first and last touching edges", "Pushes all items to the right"],
        correctAnswer: 2,
        explanation: "space-between distributes flex items so the first item is at the start, the last at the end, and equal space is between all items.",
        order: 3,
      },
      {
        questionText: "Which CSS property creates a Grid container?",
        options: ["display: grid", "grid: true", "layout: grid", "display: grid-container"],
        correctAnswer: 0,
        explanation: "display: grid creates a grid container. You then use grid-template-columns and grid-template-rows to define the grid structure.",
        order: 4,
      },
      {
        questionText: "What do CSS Custom Properties (variables) look like?",
        options: ["$primary-color: blue", "@primary: blue", "--primary-color: blue", "var-primary: blue"],
        correctAnswer: 2,
        explanation: "CSS custom properties use the -- prefix (e.g., --primary-color: blue) and are accessed with var(--primary-color).",
        order: 5,
      },
      {
        questionText: "Which CSS selector has the highest specificity?",
        options: ["Element selector (p)", "Class selector (.class)", "ID selector (#id)", "Universal selector (*)"],
        correctAnswer: 2,
        explanation: "ID selectors have specificity of (0,1,0,0), higher than class selectors (0,0,1,0) and element selectors (0,0,0,1). Inline styles are highest at (1,0,0,0).",
        order: 6,
      },
      {
        questionText: "What does 'grid-template-columns: repeat(auto-fill, minmax(200px, 1fr))' create?",
        options: ["A fixed 3-column grid", "A responsive grid that auto-creates columns filling available space", "A single-column layout", "A row-based grid"],
        correctAnswer: 1,
        explanation: "auto-fill creates as many columns as can fit, each at minimum 200px. minmax(200px, 1fr) means they grow to fill remaining space — a classic responsive card grid.",
        order: 7,
      },
    ],
  },
  {
    slug: "javascript",
    title: "JavaScript",
    description: "The language of the web — from closures and the event loop to modern ES6+.",
    category: "FRONTEND",
    icon: "Braces",
    order: 3,
    difficulty: "BEGINNER",
    questions: [
      {
        questionText: "What is a closure in JavaScript?",
        options: ["A function that closes the browser window", "A function that retains access to variables from its outer scope even after the outer function has returned", "A way to end a loop early", "A method to close a database connection"],
        correctAnswer: 1,
        explanation: "A closure is a function that 'closes over' variables from its outer (enclosing) scope, keeping them alive in memory even after the outer function has finished executing.",
        order: 1,
      },
      {
        questionText: "What is the difference between == and === in JavaScript?",
        options: ["No difference", "=== also checks type (strict equality), == does type coercion", "== is for numbers, === is for strings", "=== is slower"],
        correctAnswer: 1,
        explanation: "=== checks both value and type without coercion. == performs type coercion first. '5' == 5 is true but '5' === 5 is false. Always prefer ===.",
        order: 2,
      },
      {
        questionText: "What does 'async/await' do in JavaScript?",
        options: ["Runs code in parallel threads", "Provides synchronous-looking syntax for working with Promises", "Delays code execution", "Cancels running promises"],
        correctAnswer: 1,
        explanation: "async/await is syntactic sugar over Promises. An async function always returns a Promise. await pauses execution inside the async function until the Promise resolves.",
        order: 3,
      },
      {
        questionText: "What is the event loop in JavaScript?",
        options: ["A for loop for DOM events", "The mechanism that handles asynchronous operations by moving callbacks from task queues to the call stack when it's empty", "A way to loop through event listeners", "The browser's rendering cycle"],
        correctAnswer: 1,
        explanation: "The event loop continuously checks if the call stack is empty. When it is, it picks callbacks from the microtask queue (Promises) first, then the macrotask queue (setTimeout, I/O).",
        order: 4,
      },
      {
        questionText: "What does the spread operator (...) do?",
        options: ["Creates a deep clone", "Spreads iterable elements into individual elements", "Merges two objects destructively", "Creates a reference copy"],
        correctAnswer: 1,
        explanation: "The spread operator expands an iterable (array, string, object) into individual elements. [...arr1, ...arr2] merges arrays; {...obj1, ...obj2} merges objects (shallow).",
        order: 5,
      },
      {
        questionText: "What is the output of: console.log(typeof null)?",
        options: ["'null'", "'undefined'", "'object'", "'boolean'"],
        correctAnswer: 2,
        explanation: "'object' — this is a well-known bug in JavaScript that has existed since its creation. null is not actually an object, but typeof null returns 'object' due to a historical mistake in the implementation.",
        order: 6,
      },
      {
        questionText: "Which Array method creates a new array with elements that pass a test?",
        options: ["map()", "find()", "filter()", "reduce()"],
        correctAnswer: 2,
        explanation: "filter() returns a new array with all elements for which the callback returns true. map() transforms elements, find() returns the first match, reduce() accumulates a value.",
        order: 7,
      },
    ],
  },
  {
    slug: "react",
    title: "React",
    description: "Component-based UI development with hooks, state, and the virtual DOM.",
    category: "FRONTEND",
    icon: "Layers",
    order: 4,
    difficulty: "INTERMEDIATE",
    questions: [
      {
        questionText: "What is the purpose of the useEffect hook?",
        options: ["To create side effects like data fetching, subscriptions, and DOM manipulation", "To add CSS effects", "To create animations", "To handle form submissions"],
        correctAnswer: 0,
        explanation: "useEffect handles side effects in functional components — data fetching, setting up subscriptions, manually changing the DOM, timers, etc. It replaces componentDidMount, componentDidUpdate, and componentWillUnmount.",
        order: 1,
      },
      {
        questionText: "What does the dependency array in useEffect control?",
        options: ["The component's children", "When the effect runs — it re-runs when any listed dependency changes", "The effect's return value", "Whether the component mounts"],
        correctAnswer: 1,
        explanation: "The dependency array tells React when to re-run the effect. Empty [] means run once on mount. [value] means re-run when value changes. Omitting it means re-run after every render.",
        order: 2,
      },
      {
        questionText: "What is 'prop drilling' in React?",
        options: ["A performance optimization technique", "Passing props through multiple intermediate components that don't use them", "Drilling holes in component trees for performance", "A testing approach"],
        correctAnswer: 1,
        explanation: "Prop drilling is when you pass data through many layers of components just to reach a deeply nested component. Solutions include useContext, Redux, or Zustand for global state.",
        order: 3,
      },
      {
        questionText: "What does React.memo() do?",
        options: ["Memoizes async operations", "Prevents component re-renders when props haven't changed", "Creates a persistent memory store", "Caches API responses"],
        correctAnswer: 1,
        explanation: "React.memo is a higher-order component that memoizes the result. If a component's props don't change between renders, React reuses the last render result instead of re-rendering.",
        order: 4,
      },
      {
        questionText: "When should you use useCallback?",
        options: ["Always, for performance", "When passing a callback to memoized child components to prevent unnecessary re-renders", "Only in class components", "When using async functions"],
        correctAnswer: 1,
        explanation: "useCallback memoizes a function reference. Use it when passing callbacks to React.memo'd child components — without it, a new function reference is created each render, causing the child to re-render.",
        order: 5,
      },
      {
        questionText: "What is the virtual DOM in React?",
        options: ["A DOM element with virtual styling", "A lightweight in-memory representation of the real DOM that React uses to compute minimal updates", "A DOM API for virtual reality", "A separate rendering engine"],
        correctAnswer: 1,
        explanation: "React keeps a virtual DOM (a JavaScript object tree). When state changes, React creates a new virtual DOM, diffs it with the previous one (reconciliation), and updates only the changed parts in the real DOM.",
        order: 6,
      },
      {
        questionText: "What hook provides a way to access a DOM element directly?",
        options: ["useDom", "useState", "useRef", "useElement"],
        correctAnswer: 2,
        explanation: "useRef returns a mutable ref object with a .current property. Attaching it to a DOM element via ref={myRef} gives direct access to the DOM node for things like focus management or measuring dimensions.",
        order: 7,
      },
    ],
  },
  {
    slug: "nextjs",
    title: "Next.js",
    description: "The React framework for production — SSR, SSG, App Router, and more.",
    category: "FRONTEND",
    icon: "Triangle",
    order: 5,
    difficulty: "INTERMEDIATE",
    questions: [
      {
        questionText: "What is the difference between Server Components and Client Components in Next.js App Router?",
        options: ["Server Components run on the client with server data", "Server Components render on the server only (no JS sent to client), Client Components run on the client and can use hooks/events", "They are the same thing", "Client Components can access the database directly"],
        correctAnswer: 1,
        explanation: "Server Components render on the server only — they can access databases, filesystems, and secrets, and their code is never sent to the client. Client Components ('use client') run on the client and support interactivity.",
        order: 1,
      },
      {
        questionText: "What does 'use client' directive do in Next.js?",
        options: ["Enables SSR for that component", "Marks a component as a Client Component, enabling React hooks and browser APIs", "Disables server rendering", "Optimizes the component for client-side caching"],
        correctAnswer: 1,
        explanation: "'use client' at the top of a file marks it and all its imports as Client Components. They can use useState, useEffect, event handlers, and browser-only APIs like window and localStorage.",
        order: 2,
      },
      {
        questionText: "What is generateStaticParams used for?",
        options: ["Generating query parameters for API calls", "Pre-rendering dynamic routes at build time by providing the list of paths", "Creating static CSS parameters", "Generating environment variables"],
        correctAnswer: 1,
        explanation: "generateStaticParams returns an array of parameter values for dynamic routes. Next.js pre-renders a static HTML page for each returned value at build time, like SSG for dynamic routes.",
        order: 3,
      },
      {
        questionText: "How does file-based routing work in Next.js App Router?",
        options: ["Routes are defined in a routes.js config file", "Folders in the app/ directory become URL segments; page.jsx files define what's rendered", "Routes are defined with <Route> components", "You use a router.push() to define routes"],
        correctAnswer: 1,
        explanation: "In the App Router, the file system is the router. A folder named 'products' creates the /products segment. A page.jsx inside that folder renders at /products. [id]/page.jsx renders at /products/123.",
        order: 4,
      },
      {
        questionText: "What is the purpose of layout.jsx in the App Router?",
        options: ["A CSS layout file", "A component that wraps all pages in its directory and persists across navigation", "The homepage layout", "A configuration file for layouts"],
        correctAnswer: 1,
        explanation: "layout.jsx wraps all pages and nested layouts in its segment. It persists across navigation without re-mounting — ideal for navbars, sidebars, and providers that should stay mounted.",
        order: 5,
      },
      {
        questionText: "What cache option makes a fetch() request revalidate every 60 seconds?",
        options: ["{ cache: 'no-store' }", "{ next: { revalidate: 60 } }", "{ ttl: 60 }", "{ refresh: 60 }"],
        correctAnswer: 1,
        explanation: "{ next: { revalidate: 60 } } uses Incremental Static Regeneration (ISR) — Next.js serves a cached response but regenerates it in the background after 60 seconds if a new request comes in.",
        order: 6,
      },
      {
        questionText: "What does next/image provide over a standard <img> tag?",
        options: ["Better CSS support", "Automatic image optimization: lazy loading, format conversion (WebP/AVIF), responsive srcset, and size optimization", "Animated GIF support", "Video playback"],
        correctAnswer: 1,
        explanation: "next/image automatically optimizes images: lazy loads by default, converts to WebP/AVIF, generates responsive srcset, resizes on-demand via a built-in image optimization API.",
        order: 7,
      },
    ],
  },

  // ─────── BACKEND ───────
  {
    slug: "nodejs",
    title: "Node.js",
    description: "Server-side JavaScript — the event loop, streams, and the npm ecosystem.",
    category: "BACKEND",
    icon: "Server",
    order: 6,
    difficulty: "INTERMEDIATE",
    questions: [
      {
        questionText: "Node.js is single-threaded, so how does it handle many concurrent connections?",
        options: ["It can't — it queues all requests", "Through the event loop and non-blocking I/O — async operations are offloaded to libuv's thread pool or OS", "By spawning a thread per connection", "By using multiple V8 engines"],
        correctAnswer: 1,
        explanation: "Node.js handles concurrency via its event loop. Blocking I/O operations (file reads, network calls) are delegated to libuv's thread pool. When done, callbacks are queued on the event loop — the main thread is never blocked waiting.",
        order: 1,
      },
      {
        questionText: "What is the difference between process.nextTick() and setImmediate()?",
        options: ["They are identical", "nextTick runs before the next event loop iteration (after current operation), setImmediate runs in the check phase of the next iteration", "setImmediate runs synchronously", "nextTick is deprecated"],
        correctAnswer: 1,
        explanation: "process.nextTick() callbacks run after the current synchronous code but before the event loop continues. setImmediate() runs in the 'check' phase of the next event loop iteration. nextTick has higher priority.",
        order: 2,
      },
      {
        questionText: "What is a Node.js Stream?",
        options: ["A data visualization library", "An abstraction for working with streaming data in chunks (Readable, Writable, Duplex, Transform)", "A type of database connection", "A way to stream video"],
        correctAnswer: 1,
        explanation: "Streams process data in chunks without loading everything into memory. A Readable stream produces data (file read), Writable consumes it (file write), Duplex does both (TCP socket), Transform modifies data (gzip).",
        order: 3,
      },
      {
        questionText: "What does the 'require' function do in Node.js?",
        options: ["Requires the user to authenticate", "Loads and caches a CommonJS module", "Marks code as required for execution", "Validates function arguments"],
        correctAnswer: 1,
        explanation: "require() loads a CommonJS module, executing its code and returning module.exports. Node.js caches modules after first load — subsequent require() calls return the cached version.",
        order: 4,
      },
      {
        questionText: "What is the EventEmitter in Node.js?",
        options: ["A DOM event listener", "A class that implements the observer pattern — objects emit named events and listeners respond", "A browser event system", "A way to emit CSS events"],
        correctAnswer: 1,
        explanation: "EventEmitter is Node.js's implementation of the observer pattern. Objects extend EventEmitter to emit named events (emitter.emit('data', payload)) and listeners subscribe with on('data', handler).",
        order: 5,
      },
      {
        questionText: "How do you use all CPU cores in a Node.js application?",
        options: ["Node.js automatically uses all cores", "Use the cluster module to fork worker processes, one per CPU core", "Set NODE_WORKERS=max environment variable", "Use multiple Node.js installations"],
        correctAnswer: 1,
        explanation: "Node.js is single-threaded. To use all CPU cores, use the cluster module (or PM2 cluster mode) to fork worker processes. Each worker is a full Node.js process listening on the same port.",
        order: 6,
      },
      {
        questionText: "What is the purpose of package.json's 'scripts' field?",
        options: ["Loads JavaScript files", "Defines shorthand npm commands like 'npm run dev', 'npm test'", "Lists script dependencies", "Configures the package bundler"],
        correctAnswer: 1,
        explanation: "The scripts field maps shorthand names to shell commands run with 'npm run <name>'. Built-in scripts (test, start) can be run without 'run'. Scripts have access to locally installed .bin executables.",
        order: 7,
      },
    ],
  },
  {
    slug: "express",
    title: "Express.js",
    description: "Minimal Node.js web framework — routing, middleware, and REST APIs.",
    category: "BACKEND",
    icon: "Globe",
    order: 7,
    difficulty: "INTERMEDIATE",
    questions: [
      {
        questionText: "What is middleware in Express.js?",
        options: ["Database connection pooling", "Functions that have access to req, res, and next — forming a request processing pipeline", "A templating engine", "CSS middleware for styling"],
        correctAnswer: 1,
        explanation: "Middleware functions execute in sequence for each request. They can modify req/res, end the cycle (send response), or call next() to pass to the next middleware. Used for logging, auth, parsing, CORS, error handling.",
        order: 1,
      },
      {
        questionText: "What does next(err) do in Express middleware?",
        options: ["Calls the next middleware regardless", "Skips to error-handling middleware (a function with 4 params: err, req, res, next)", "Logs the error and continues", "Throws the error to the client"],
        correctAnswer: 1,
        explanation: "Calling next(err) skips regular middleware and passes control to error-handling middleware, which has the signature (err, req, res, next). This centralizes error handling.",
        order: 2,
      },
      {
        questionText: "What does express.Router() do?",
        options: ["Configures the URL router", "Creates a modular, mini Express application for defining grouped routes", "Handles client-side routing", "Defines the base URL for all routes"],
        correctAnswer: 1,
        explanation: "express.Router() creates a modular route handler. You define routes on the router instance and mount it on a path in the main app, keeping route files clean and organized.",
        order: 3,
      },
      {
        questionText: "How do you access URL parameters in Express? (e.g., /users/:id)",
        options: ["req.query.id", "req.params.id", "req.body.id", "req.url.id"],
        correctAnswer: 1,
        explanation: "req.params contains route parameters (dynamic path segments). For /users/:id, req.params.id holds the value. req.query holds query string (?key=value), req.body holds POST body.",
        order: 4,
      },
      {
        questionText: "What middleware is needed to parse JSON request bodies?",
        options: ["express.body()", "bodyParser.json()", "express.json()", "app.parseJson()"],
        correctAnswer: 2,
        explanation: "express.json() is built-in middleware (since Express 4.16+) that parses incoming requests with JSON payloads. It populates req.body with the parsed JavaScript object.",
        order: 5,
      },
      {
        questionText: "What is the correct order for Express middleware?",
        options: ["Order doesn't matter in Express", "Middleware executes in the order it's added with app.use()", "Error handlers run first", "Route handlers always run before middleware"],
        correctAnswer: 1,
        explanation: "Express executes middleware in the order they're registered with app.use() or route methods. This is why global middleware (logging, CORS, body parsing) must be registered before route handlers.",
        order: 6,
      },
    ],
  },

  // ─────── DATABASES ───────
  {
    slug: "sql-fundamentals",
    title: "SQL Fundamentals",
    description: "Querying, joining, aggregating, and understanding relational databases.",
    category: "DATABASES",
    icon: "Table2",
    order: 8,
    difficulty: "BEGINNER",
    questions: [
      {
        questionText: "What does the SQL JOIN clause do?",
        options: ["Combines rows from two or more tables based on a related column", "Merges two tables permanently", "Adds a new column to a table", "Joins two databases together"],
        correctAnswer: 0,
        explanation: "JOIN combines rows from two or more tables based on a matching column (usually a foreign key). The most common type is INNER JOIN, which returns only matching rows.",
        order: 1,
      },
      {
        questionText: "What is the difference between WHERE and HAVING?",
        options: ["They are identical", "WHERE filters rows before grouping, HAVING filters groups after GROUP BY", "HAVING filters individual rows, WHERE filters groups", "WHERE is for strings, HAVING is for numbers"],
        correctAnswer: 1,
        explanation: "WHERE filters individual rows before aggregation. HAVING filters groups after GROUP BY. You use HAVING to filter based on aggregate values like HAVING COUNT(*) > 5.",
        order: 2,
      },
      {
        questionText: "What does a PRIMARY KEY constraint do?",
        options: ["Makes a column case-sensitive", "Uniquely identifies each row and prevents NULL values in that column", "Creates a foreign key reference", "Encrypts the column data"],
        correctAnswer: 1,
        explanation: "A PRIMARY KEY uniquely identifies each row. It creates an implicit UNIQUE constraint and NOT NULL constraint. A table can have only one primary key (but it can be composite).",
        order: 3,
      },
      {
        questionText: "What is a LEFT JOIN?",
        options: ["Joins tables from left to right by name", "Returns all rows from the left table, and matching rows from the right — NULLs where no match", "Returns only left table rows with no matches", "Returns only matching rows from both tables"],
        correctAnswer: 1,
        explanation: "LEFT JOIN returns all rows from the left table, even if there's no match in the right table. Unmatched rows from the right side appear as NULLs. Great for finding records with or without related data.",
        order: 4,
      },
      {
        questionText: "What does the DISTINCT keyword do?",
        options: ["Sorts results in descending order", "Removes duplicate rows from the result set", "Selects only primary key columns", "Creates a distinct index"],
        correctAnswer: 1,
        explanation: "SELECT DISTINCT removes duplicate rows from the result. It compares all selected columns to determine duplicates. It has a performance cost on large datasets.",
        order: 5,
      },
      {
        questionText: "What are the ACID properties in database transactions?",
        options: ["Automation, Consistency, Isolation, Delivery", "Atomicity, Consistency, Isolation, Durability", "Access, Control, Index, Data", "Async, Concurrent, Indexed, Durable"],
        correctAnswer: 1,
        explanation: "ACID: Atomicity (all or nothing), Consistency (data stays valid), Isolation (concurrent transactions don't interfere), Durability (committed data persists even on failure). These guarantee reliable transactions.",
        order: 6,
      },
      {
        questionText: "What is a database index?",
        options: ["A list of all table names", "A data structure that speeds up data retrieval at the cost of additional storage and write overhead", "A primary key constraint", "A way to back up the database"],
        correctAnswer: 1,
        explanation: "An index is a separate data structure (usually B-tree) that allows the database to find rows quickly without scanning the whole table. Speeds up reads but slightly slows writes. Create on frequently queried columns.",
        order: 7,
      },
    ],
  },
  {
    slug: "nosql-concepts",
    title: "NoSQL Concepts",
    description: "Document, key-value, column-family, and graph databases — when to use what.",
    category: "DATABASES",
    icon: "DatabaseZap",
    order: 9,
    difficulty: "INTERMEDIATE",
    questions: [
      {
        questionText: "What are the four main types of NoSQL databases?",
        options: ["Relational, Object, Flat, Hierarchical", "Document, Key-Value, Column-family, Graph", "SQL, NoSQL, NewSQL, OldSQL", "Indexed, Hashed, Sorted, Cached"],
        correctAnswer: 1,
        explanation: "Document stores (MongoDB) store JSON-like docs. Key-Value (Redis) store simple pairs. Column-family (Cassandra) store data in columns. Graph (Neo4j) store nodes and relationships.",
        order: 1,
      },
      {
        questionText: "What does the CAP theorem state?",
        options: ["You can have all three: Consistency, Availability, and Partition tolerance", "Distributed systems can guarantee at most two of: Consistency, Availability, Partition tolerance", "CAP stands for Cache, Access, Performance", "All databases must be consistent and available"],
        correctAnswer: 1,
        explanation: "The CAP theorem proves that a distributed system can only guarantee two of the three: Consistency (all nodes see the same data), Availability (every request gets a response), Partition tolerance (system works despite network splits).",
        order: 2,
      },
      {
        questionText: "When would you choose Redis over MongoDB?",
        options: ["When you need complex queries on large documents", "When you need ultra-fast reads/writes for simple data structures, caching, sessions, or rate limiting", "For storing large binary files", "For multi-table relational queries"],
        correctAnswer: 1,
        explanation: "Redis is an in-memory data store with microsecond latency, perfect for caching, sessions, rate limiting, real-time leaderboards, and pub/sub. MongoDB is better for flexible document storage with complex querying needs.",
        order: 3,
      },
      {
        questionText: "What is 'eventual consistency' in distributed systems?",
        options: ["Data is immediately consistent across all nodes", "Given enough time without updates, all replicas will converge to the same value", "Consistency is never guaranteed", "Data is consistent only during transactions"],
        correctAnswer: 1,
        explanation: "Eventual consistency means updates propagate asynchronously — different nodes may temporarily return different values, but they will eventually converge. Many NoSQL databases (DynamoDB, Cassandra) use this model for availability.",
        order: 4,
      },
      {
        questionText: "What is horizontal scaling (sharding) in NoSQL databases?",
        options: ["Adding more RAM to a single server", "Distributing data across multiple servers/nodes to handle larger datasets", "Scaling the database horizontally in the UI", "Adding more CPU cores to one machine"],
        correctAnswer: 1,
        explanation: "Sharding splits data across multiple servers (shards) based on a shard key. Each shard holds a subset of the data. This allows horizontal scaling — adding more servers instead of bigger hardware.",
        order: 5,
      },
      {
        questionText: "What is the key advantage of document databases over relational databases?",
        options: ["Faster SQL queries", "Flexible schema — documents in the same collection can have different fields without a migration", "Better ACID compliance", "Lower storage costs"],
        correctAnswer: 1,
        explanation: "Document databases store schema-less JSON documents. You can add fields to new documents without modifying existing ones or running ALTER TABLE migrations. This flexibility is great for evolving data models.",
        order: 6,
      },
    ],
  },
  {
    slug: "mongodb",
    title: "MongoDB",
    description: "Document database — CRUD, aggregation pipelines, and Mongoose ODM.",
    category: "DATABASES",
    icon: "Leaf",
    order: 10,
    difficulty: "INTERMEDIATE",
    questions: [
      {
        questionText: "What is an aggregation pipeline in MongoDB?",
        options: ["A method to pipe Node.js streams into MongoDB", "A series of stages that process documents sequentially, transforming data", "A way to aggregate multiple databases", "A deployment pipeline for MongoDB Atlas"],
        correctAnswer: 1,
        explanation: "An aggregation pipeline is an array of stages ($match, $group, $sort, $lookup, $project, etc.) that process documents in sequence. Each stage transforms the documents passed to the next stage.",
        order: 1,
      },
      {
        questionText: "What is the $lookup stage in MongoDB aggregation?",
        options: ["Looks up a value in an index", "Performs a left outer join between two collections", "Searches for documents matching a regex", "Looks up geo coordinates"],
        correctAnswer: 1,
        explanation: "$lookup performs a left outer join — for each document in the local collection, it adds an array field containing matching documents from a foreign collection. It's MongoDB's equivalent of SQL JOIN.",
        order: 2,
      },
      {
        questionText: "What is the difference between find() and findOne() in MongoDB?",
        options: ["findOne() is faster", "find() returns a cursor to all matching documents, findOne() returns the first matching document", "findOne() searches by ID only", "find() is deprecated"],
        correctAnswer: 1,
        explanation: "find() returns a cursor (iterable) to all matching documents. findOne() returns the first matching document directly (or null if not found). findOne() is equivalent to find().limit(1).next().",
        order: 3,
      },
      {
        questionText: "What does the $set operator do in an update operation?",
        options: ["Replaces the entire document", "Sets (or creates) specific fields without affecting other fields", "Sets the document's _id", "Creates a new collection"],
        correctAnswer: 1,
        explanation: "$set updates specific fields. db.users.updateOne({_id: id}, {$set: {name: 'Alice'}}) only changes the name field, leaving all other fields intact. Without $set, the entire document would be replaced.",
        order: 4,
      },
      {
        questionText: "What is a MongoDB ObjectId?",
        options: ["A UUID generated by the application", "A 12-byte BSON type used as the default _id, encoding timestamp, machine ID, process ID, and counter", "A sequential auto-increment number", "A hash of the document contents"],
        correctAnswer: 1,
        explanation: "MongoDB's ObjectId is a 12-byte BSON type: 4 bytes timestamp, 5 bytes random (machine+process), 3 bytes counter. It's sortable by creation time and globally unique without coordination.",
        order: 5,
      },
      {
        questionText: "What does Mongoose's populate() method do?",
        options: ["Fills a database with test data", "Automatically replaces reference ObjectIds with the actual referenced documents", "Populates a form with database values", "Creates a data population script"],
        correctAnswer: 1,
        explanation: "populate() resolves document references. If a Post has author: ObjectId, populate('author') fetches the User document and replaces the ObjectId with the actual user object in the query result.",
        order: 6,
      },
      {
        questionText: "When do MongoDB transactions require a replica set?",
        options: ["Always", "Only for write operations", "Multi-document ACID transactions require a replica set or sharded cluster", "Transactions are not supported in MongoDB"],
        correctAnswer: 2,
        explanation: "MongoDB multi-document transactions (similar to SQL transactions) require a replica set (or sharded cluster). Single-document operations are always atomic without requiring a replica set.",
        order: 7,
      },
    ],
  },
  {
    slug: "postgresql",
    title: "PostgreSQL",
    description: "Advanced relational database — JSONB, full-text search, RLS, and performance.",
    category: "DATABASES",
    icon: "Database",
    order: 11,
    difficulty: "ADVANCED",
    questions: [
      {
        questionText: "What is MVCC in PostgreSQL?",
        options: ["Multi-Version CSS Compiler", "Multi-Version Concurrency Control — readers don't block writers and writers don't block readers", "Maximum Vertical Column Count", "Managed View Cache Control"],
        correctAnswer: 1,
        explanation: "MVCC maintains multiple versions of rows. Each transaction sees a snapshot of the database at its start time. This allows concurrent reads and writes without locks, greatly improving performance.",
        order: 1,
      },
      {
        questionText: "What is JSONB in PostgreSQL?",
        options: ["JavaScript Object Notation Binary — stores JSON as binary for efficient querying and indexing", "A JSON validation library for Postgres", "A JSON-based backup format", "JavaScript Bridge for Postgres"],
        correctAnswer: 0,
        explanation: "JSONB stores JSON as decomposed binary — faster to query than JSON type, supports indexing via GIN, and allows operators like @> (contains), -> (get field), ->> (get as text). Essential for flexible schemas in Postgres.",
        order: 2,
      },
      {
        questionText: "What is Row-Level Security (RLS) in PostgreSQL?",
        options: ["Restricts the number of rows in a table", "Policies that control which rows users can SELECT/INSERT/UPDATE/DELETE based on their identity", "Encrypts rows at the storage level", "Limits row size in bytes"],
        correctAnswer: 1,
        explanation: "RLS policies filter rows based on the current user's context. With RLS enabled and a policy like 'USING (user_id = current_user_id())', users can only see/modify their own rows — ideal for multi-tenant SaaS.",
        order: 3,
      },
      {
        questionText: "What does EXPLAIN ANALYZE do?",
        options: ["Explains the SQL syntax errors", "Executes the query and shows the actual query execution plan with timing and row estimates", "Analyzes table statistics only", "Shows the schema of a table"],
        correctAnswer: 1,
        explanation: "EXPLAIN ANALYZE actually runs the query and shows the execution plan with actual timing (not just estimates). Use it to identify sequential scans, missing indexes, and slow join strategies.",
        order: 4,
      },
      {
        questionText: "What is a GIN index in PostgreSQL?",
        options: ["General Index Node for sequential data", "Generalized Inverted Index — optimized for full-text search, JSONB, and array column queries", "A lightweight index for small tables", "Generic Integer Node index"],
        correctAnswer: 1,
        explanation: "GIN (Generalized Inverted Index) stores a mapping of values to document locations. It's optimized for searching within composite values — JSONB fields, tsvector for full-text, and arrays.",
        order: 5,
      },
      {
        questionText: "What is a window function in PostgreSQL?",
        options: ["A function for GUI window management", "A function that performs calculations across rows related to the current row without collapsing them", "A function to view table metadata", "A function that works only on windowed time data"],
        correctAnswer: 1,
        explanation: "Window functions (RANK(), ROW_NUMBER(), LAG(), LEAD(), SUM() OVER()) calculate values across a set of rows related to the current row, maintaining individual rows in the result (unlike GROUP BY which collapses rows).",
        order: 6,
      },
    ],
  },
  {
    slug: "prisma-orm",
    title: "Prisma ORM",
    description: "Type-safe database client for Node.js — schema, migrations, and queries.",
    category: "DATABASES",
    icon: "Wand2",
    order: 12,
    difficulty: "INTERMEDIATE",
    questions: [
      {
        questionText: "What are the three main components of Prisma?",
        options: ["Prisma Model, Prisma View, Prisma Controller", "Prisma Client, Prisma Migrate, Prisma Studio", "Prisma Schema, Prisma ORM, Prisma DB", "Prisma Query, Prisma Seed, Prisma Deploy"],
        correctAnswer: 1,
        explanation: "Prisma Client is the auto-generated query builder. Prisma Migrate manages database schema migrations. Prisma Studio is a visual GUI to browse and edit data.",
        order: 1,
      },
      {
        questionText: "What is an upsert operation in Prisma?",
        options: ["Insert a new record if it exists, skip otherwise", "Update if found, insert if not found — based on a unique identifier", "Delete and re-insert a record", "Update a record and sort results"],
        correctAnswer: 1,
        explanation: "prisma.model.upsert({ where, update, create }) — if a record matching 'where' exists, it applies 'update'; if not, it creates with 'create'. Prevents duplicate record errors.",
        order: 2,
      },
      {
        questionText: "What does the 'include' option do in Prisma queries?",
        options: ["Adds new fields to the model", "Eager-loads related records (relations) alongside the queried model", "Includes raw SQL in the query", "Merges multiple query results"],
        correctAnswer: 1,
        explanation: "include loads related models. prisma.post.findMany({ include: { author: true } }) returns each post with its full author object fetched in the same query (like JOIN).",
        order: 3,
      },
      {
        questionText: "What is the difference between 'prisma migrate dev' and 'prisma db push'?",
        options: ["They are identical commands", "migrate dev creates SQL migration files for version control; db push applies schema changes directly without migration history", "db push is for production, migrate dev for development", "migrate dev is faster"],
        correctAnswer: 1,
        explanation: "prisma migrate dev creates .sql migration files committed to source control — ideal for production. prisma db push directly syncs the schema to the DB without creating files — great for prototyping.",
        order: 4,
      },
      {
        questionText: "How do you perform a Prisma interactive transaction?",
        options: ["prisma.transaction.begin()", "prisma.$transaction(async (tx) => { ... })", "prisma.atomic(() => { ... })", "prisma.begin().commit()"],
        correctAnswer: 1,
        explanation: "prisma.$transaction(async (tx) => {...}) provides an interactive transaction. 'tx' is a Prisma client scoped to the transaction. If the callback throws, the transaction is rolled back automatically.",
        order: 5,
      },
      {
        questionText: "What does the @default(cuid()) attribute do in Prisma schema?",
        options: ["Creates a UUID v4 default value", "Generates a collision-resistant unique ID as the default field value", "Creates a sequential integer ID", "Sets a CUID validation rule"],
        correctAnswer: 1,
        explanation: "@default(cuid()) auto-generates a collision-resistant unique ID (shorter than UUID, URL-safe) when a record is created. Alternatives: @default(uuid()), @default(autoincrement()).",
        order: 6,
      },
    ],
  },
  {
    slug: "mongoose",
    title: "Mongoose ODM",
    description: "Schema-based modeling for MongoDB — schemas, hooks, virtuals, and population.",
    category: "DATABASES",
    icon: "GitBranch",
    order: 13,
    difficulty: "INTERMEDIATE",
    questions: [
      {
        questionText: "What is a Mongoose Schema?",
        options: ["A JSON backup of the database", "A blueprint that defines the structure, types, defaults, and validators for documents in a collection", "A database schema file", "A way to define indexes"],
        correctAnswer: 1,
        explanation: "A Mongoose Schema defines the shape of documents — field names, types (String, Number, ObjectId, etc.), required constraints, default values, validators, and methods. It's then compiled into a Model.",
        order: 1,
      },
      {
        questionText: "What is a Mongoose pre('save') hook?",
        options: ["A function that runs before the database is saved to disk", "Middleware that runs before a document's save() is executed — used for hashing passwords, setting timestamps", "A backup hook before model deletion", "A hook that pre-validates fields"],
        correctAnswer: 1,
        explanation: "pre('save') runs before a document is saved to MongoDB. Common uses: hashing passwords (check isModified('password')), setting computed fields, or validating cross-field constraints.",
        order: 2,
      },
      {
        questionText: "What are Mongoose virtuals?",
        options: ["Virtual machine configurations", "Computed properties defined on a schema that are not stored in MongoDB — they are derived on the fly", "Placeholder fields for future use", "Virtual indexes"],
        correctAnswer: 1,
        explanation: "Virtuals are properties computed from other fields, not stored in the DB. Example: a 'fullName' virtual computed from firstName + lastName. Use schema.virtual('fullName').get(() => ...) to define them.",
        order: 3,
      },
      {
        questionText: "What does .lean() do in a Mongoose query?",
        options: ["Reduces memory by dropping null fields", "Returns plain JavaScript objects instead of Mongoose Documents — faster but without Document methods/virtuals", "Selects only lean/essential fields", "Applies a lean validation mode"],
        correctAnswer: 1,
        explanation: ".lean() skips Mongoose's Document hydration — returns plain JS objects instead of full Mongoose Document instances. 2-10x faster for read-only queries since you don't need methods, virtuals, or save().",
        order: 4,
      },
      {
        questionText: "How do you define a many-to-many relationship in Mongoose?",
        options: ["Using a JOIN table schema", "By storing arrays of ObjectId references in both schemas and using populate() to resolve them", "Using the @ManyToMany decorator", "Mongoose doesn't support many-to-many"],
        correctAnswer: 1,
        explanation: "Mongoose models many-to-many by embedding arrays of ObjectIds. Example: User has posts: [{ type: ObjectId, ref: 'Post' }] and Post has tags: [{ type: ObjectId, ref: 'Tag' }]. Use populate() to resolve.",
        order: 5,
      },
      {
        questionText: "What is the purpose of Mongoose's 'timestamps: true' option?",
        options: ["Adds a timestamp validator", "Automatically adds createdAt and updatedAt Date fields managed by Mongoose", "Records the time of each field access", "Adds Unix timestamp integers to the schema"],
        correctAnswer: 1,
        explanation: "{ timestamps: true } in the schema options tells Mongoose to automatically add and manage createdAt (set once on create) and updatedAt (updated on every save) fields.",
        order: 6,
      },
    ],
  },

  // ─────── ADVANCED BACKEND ───────
  {
    slug: "cron-jobs",
    title: "Cron Jobs",
    description: "Scheduled background tasks — expressions, node-cron, and distributed locking.",
    category: "ADVANCED_BACKEND",
    icon: "Clock",
    order: 14,
    difficulty: "INTERMEDIATE",
    questions: [
      {
        questionText: "What does '0 2 * * 1' mean as a cron expression?",
        options: ["Every 2 minutes on Mondays", "At 2:00 AM every Monday", "At 2:00 AM every day", "On the 2nd minute of every hour on Mondays"],
        correctAnswer: 1,
        explanation: "Cron: minute(0) hour(2) day-of-month(*) month(*) day-of-week(1=Monday). So: at 2:00 AM every Monday.",
        order: 1,
      },
      {
        questionText: "What does '*/5 * * * *' mean in a cron expression?",
        options: ["Every 5 hours", "Every 5 minutes", "5 times per day", "Every 5 seconds"],
        correctAnswer: 1,
        explanation: "The */ notation means 'every'. */5 in the minutes field means every 5 minutes. */2 in hours means every 2 hours.",
        order: 2,
      },
      {
        questionText: "Why is idempotency important for cron jobs?",
        options: ["It makes jobs run faster", "Jobs may be triggered multiple times (network issues, restarts) — idempotent jobs produce the same result regardless of how many times they run", "It reduces cron job complexity", "It's required for database access"],
        correctAnswer: 1,
        explanation: "In distributed systems, jobs may run more than once due to retries, overlapping executions, or race conditions. Idempotent jobs — same result no matter how many times they run — prevent duplicate emails, double charges, etc.",
        order: 3,
      },
      {
        questionText: "How do you prevent duplicate execution of cron jobs across multiple server instances?",
        options: ["Use a single server", "Implement distributed locking using Redis SET NX to ensure only one instance runs the job", "Disable the cron on all but one server manually", "Use database timestamps to skip re-runs"],
        correctAnswer: 1,
        explanation: "Redis SET NX (Set if Not eXists) creates a distributed lock. Only the instance that successfully sets the lock runs the job. Combined with TTL expiry, this prevents deadlocks if the job crashes.",
        order: 4,
      },
      {
        questionText: "What is the difference between node-cron and Bull MQ for scheduled tasks?",
        options: ["They are identical", "node-cron is in-process and doesn't persist; BullMQ stores jobs in Redis with persistence, retries, and monitoring", "BullMQ is only for batch jobs", "node-cron supports distributed execution natively"],
        correctAnswer: 1,
        explanation: "node-cron runs schedules in memory — lost on restart. BullMQ persists jobs in Redis, supports delayed/scheduled jobs with retries, dashboards, and works across multiple processes.",
        order: 5,
      },
      {
        questionText: "How do you schedule a job to run every weekday at 9 AM?",
        options: ["'0 9 * * 1-5'", "'9 0 * * 1-5'", "'0 9 1-5 * *'", "'*/9 * * * 1-5'"],
        correctAnswer: 0,
        explanation: "'0 9 * * 1-5' — minute(0) hour(9) day-of-month(*) month(*) day-of-week(1-5 = Monday-Friday). The range 1-5 selects Monday through Friday.",
        order: 6,
      },
    ],
  },
  {
    slug: "bullmq",
    title: "BullMQ",
    description: "Redis-based job queues for Node.js — workers, retries, and monitoring.",
    category: "ADVANCED_BACKEND",
    icon: "ListTodo",
    order: 15,
    difficulty: "ADVANCED",
    questions: [
      {
        questionText: "What does BullMQ use as its backing store?",
        options: ["PostgreSQL", "MongoDB", "Redis", "In-memory only"],
        correctAnswer: 2,
        explanation: "BullMQ uses Redis for persistent job storage. Jobs are stored as Redis Streams and sorted sets. This provides durability, atomic operations, and enables distributed processing across multiple Node.js processes.",
        order: 1,
      },
      {
        questionText: "What happens when a BullMQ job fails and has 'attempts: 3' configured?",
        options: ["The job is deleted", "BullMQ retries the job up to 3 times before moving it to the failed queue", "The job runs exactly 3 times regardless of success", "It sends an error email after 3 attempts"],
        correctAnswer: 1,
        explanation: "BullMQ automatically retries failed jobs up to the configured attempts count. Combined with backoff (exponential or fixed), it retries with increasing delays. After all attempts are exhausted, the job moves to 'failed' state.",
        order: 2,
      },
      {
        questionText: "What is the purpose of 'concurrency' in a BullMQ Worker?",
        options: ["Number of queues to connect to", "How many jobs the worker processes simultaneously", "Number of Redis connections to open", "The number of retries for concurrent jobs"],
        correctAnswer: 1,
        explanation: "concurrency controls how many jobs a single Worker instance processes in parallel. Default is 1. Setting concurrency: 5 allows 5 jobs to be active simultaneously in that worker process.",
        order: 3,
      },
      {
        questionText: "What is a delayed job in BullMQ?",
        options: ["A job that ran slowly", "A job that won't be processed until a specified time in the future", "A job waiting in the queue", "A job with low priority"],
        correctAnswer: 1,
        explanation: "Adding a job with { delay: 86400000 } (24 hours in ms) schedules it to become active after that delay. BullMQ's QueueScheduler moves delayed jobs to the active queue when their time arrives.",
        order: 4,
      },
      {
        questionText: "What is a BullMQ Flow?",
        options: ["A queue of flows", "A tree of jobs with parent-child dependencies — parent waits for all children to complete", "A way to chain multiple queues", "A visual flow builder plugin"],
        correctAnswer: 1,
        explanation: "BullMQ Flows (FlowProducer) create parent-child job trees. A parent job only becomes active after all its children complete successfully. This enables complex multi-step workflows with dependencies.",
        order: 5,
      },
      {
        questionText: "What does job.updateProgress() do?",
        options: ["Updates the job's priority", "Reports the job's completion percentage for monitoring dashboards", "Moves the job to a different queue", "Updates the job's retry count"],
        correctAnswer: 1,
        explanation: "job.updateProgress(value) lets workers report progress (0-100 or a custom object). QueueEvents listeners can subscribe to 'progress' events, enabling real-time progress tracking in dashboards.",
        order: 6,
      },
    ],
  },
  {
    slug: "pubsub-pattern",
    title: "Pub/Sub Pattern",
    description: "Event-driven messaging — Redis Pub/Sub, EventEmitter, and distributed messaging.",
    category: "ADVANCED_BACKEND",
    icon: "Radio",
    order: 16,
    difficulty: "ADVANCED",
    questions: [
      {
        questionText: "What is the key difference between Pub/Sub and a message queue?",
        options: ["Pub/Sub is slower", "In Pub/Sub, messages are delivered to ALL active subscribers; in queues, each message is consumed by ONE worker", "Message queues are only for emails", "Pub/Sub requires Redis"],
        correctAnswer: 1,
        explanation: "Pub/Sub is a broadcast model — every active subscriber receives each message. Message queues (like BullMQ) deliver each message to exactly one consumer. Choose Pub/Sub for notifications/events, queues for task distribution.",
        order: 1,
      },
      {
        questionText: "What is a major limitation of Redis Pub/Sub?",
        options: ["It only supports one subscriber per channel", "Messages are not persisted — subscribers that are offline miss all messages", "It requires MongoDB", "Redis Pub/Sub doesn't support multiple channels"],
        correctAnswer: 1,
        explanation: "Redis Pub/Sub is fire-and-forget with no persistence. If a subscriber disconnects and reconnects, it misses all messages sent during downtime. For durable messaging, use Redis Streams or Kafka.",
        order: 2,
      },
      {
        questionText: "What is the difference between Redis Pub/Sub and Redis Streams?",
        options: ["They are identical", "Streams persist messages, support consumer groups, and allow replaying — Pub/Sub is ephemeral and has no message history", "Streams are faster than Pub/Sub", "Pub/Sub supports consumer groups, Streams don't"],
        correctAnswer: 1,
        explanation: "Redis Streams store messages persistently as an append-only log. Consumer groups allow distributed processing with acknowledgements. Pub/Sub is ephemeral — perfect for real-time notifications but not for reliable delivery.",
        order: 3,
      },
      {
        questionText: "What is fan-out in messaging?",
        options: ["A cooling fan in server hardware", "Delivering one message to multiple subscribers/queues simultaneously", "A way to filter messages", "Sending messages in batches"],
        correctAnswer: 1,
        explanation: "Fan-out distributes a single event to multiple consumers. Example: when an order is placed, fan-out delivers the event to email service, inventory service, analytics service, and notification service simultaneously.",
        order: 4,
      },
      {
        questionText: "When would you choose Google Cloud Pub/Sub over Redis Pub/Sub?",
        options: ["When you need lower latency", "When you need durable, at-least-once delivery with message replay for globally distributed microservices", "For in-process messaging", "When Redis is too expensive"],
        correctAnswer: 1,
        explanation: "Cloud Pub/Sub provides durable messaging, at-least-once delivery guarantees, message retention (replay), global distribution, and auto-scaling. Redis Pub/Sub is ephemeral and better for low-latency, in-datacenter use.",
        order: 5,
      },
    ],
  },
  {
    slug: "websockets",
    title: "WebSockets",
    description: "Full-duplex real-time communication — Socket.IO, rooms, and scaling.",
    category: "ADVANCED_BACKEND",
    icon: "Wifi",
    order: 17,
    difficulty: "ADVANCED",
    questions: [
      {
        questionText: "How does a WebSocket connection start?",
        options: ["A direct TCP connection on port 80", "An HTTP Upgrade handshake — the client sends an Upgrade: websocket header and the server responds with 101 Switching Protocols", "A UDP handshake", "A TLS certificate exchange"],
        correctAnswer: 1,
        explanation: "WebSocket begins as an HTTP request with an 'Upgrade: websocket' header. The server responds with HTTP 101 Switching Protocols, and from then on both sides communicate over the persistent WebSocket protocol.",
        order: 1,
      },
      {
        questionText: "What is the difference between WebSockets and Server-Sent Events (SSE)?",
        options: ["They are identical", "WebSockets are full-duplex (both directions); SSE is one-directional (server to client only) over HTTP", "SSE supports bidirectional communication", "WebSockets only work in browsers"],
        correctAnswer: 1,
        explanation: "WebSockets are bidirectional — both client and server can send messages. SSE is a one-way stream from server to client over HTTP (text/event-stream). SSE is simpler, works through HTTP/2, but only for server-push scenarios.",
        order: 2,
      },
      {
        questionText: "What is a Socket.IO room?",
        options: ["A virtual chat room with a UI", "A named group of socket connections — broadcast to a room delivers the message to all sockets that joined it", "A namespace division", "A separate Socket.IO server"],
        correctAnswer: 1,
        explanation: "Rooms are arbitrary channels that sockets can join/leave. socket.join('room1') adds the socket to room1. io.to('room1').emit('message', data) delivers to all sockets in room1.",
        order: 3,
      },
      {
        questionText: "Why do you need a Redis adapter for Socket.IO in a multi-server deployment?",
        options: ["Redis makes Socket.IO faster", "Without it, socket rooms only exist in one server's memory — the Redis adapter syncs room membership and broadcasts across all server instances", "Socket.IO requires Redis to work", "Redis provides authentication for sockets"],
        correctAnswer: 1,
        explanation: "In a multi-server setup, a client on Server A and a client on Server B can't communicate directly. The Redis adapter uses Redis Pub/Sub to propagate events between instances so rooms work across all servers.",
        order: 4,
      },
      {
        questionText: "What is a Socket.IO heartbeat/ping?",
        options: ["A way to send urgent messages", "Periodic pings from server to client to detect dead connections and trigger reconnection", "A health check for the server", "A way to measure connection speed"],
        correctAnswer: 1,
        explanation: "Socket.IO sends periodic ping frames. If the client doesn't respond with a pong within the timeout, Socket.IO considers the connection dead, fires a 'disconnect' event, and the client automatically reconnects.",
        order: 5,
      },
    ],
  },
  {
    slug: "webrtc",
    title: "WebRTC",
    description: "Peer-to-peer video, audio, and data — ICE, STUN, TURN, and signaling.",
    category: "ADVANCED_BACKEND",
    icon: "Video",
    order: 18,
    difficulty: "ADVANCED",
    questions: [
      {
        questionText: "What is the role of a STUN server in WebRTC?",
        options: ["Relays media between peers", "Helps peers discover their public IP address and port for NAT traversal", "Encrypts the media stream", "Authenticates users before a call"],
        correctAnswer: 1,
        explanation: "STUN (Session Traversal Utilities for NAT) tells a peer its public IP and port as seen from outside the NAT. This info is used as ICE candidates for direct P2P connection. STUN is stateless and cheap.",
        order: 1,
      },
      {
        questionText: "When is a TURN server required?",
        options: ["Always, for security", "When peers are behind symmetric NATs or strict firewalls that block direct P2P connections", "Only for video calls", "When the STUN server is unavailable"],
        correctAnswer: 1,
        explanation: "TURN (Traversal Using Relays around NAT) relays all media through the TURN server when direct P2P fails. It's a fallback for strict corporate firewalls and symmetric NATs. TURN servers are expensive (bandwidth costs).",
        order: 2,
      },
      {
        questionText: "What is SDP in WebRTC?",
        options: ["Secure Data Protocol", "Session Description Protocol — describes the media capabilities, codecs, and connection info exchanged during offer/answer", "Streaming Data Package", "Socket Description Package"],
        correctAnswer: 1,
        explanation: "SDP describes the session: supported audio/video codecs, bitrates, ICE candidates, DTLS fingerprints. The caller creates an SDP offer, the callee creates an SDP answer — exchanged via the signaling server.",
        order: 3,
      },
      {
        questionText: "What is ICE in WebRTC?",
        options: ["In-Call Encryption", "Interactive Connectivity Establishment — finds the best connection path between peers by trying all candidate addresses", "Internet Connection Explorer", "Initial Call Exchange"],
        correctAnswer: 1,
        explanation: "ICE collects all possible connection paths (candidates): local addresses, STUN-discovered public addresses, TURN relay addresses. It tests them all and selects the best working path for the connection.",
        order: 4,
      },
      {
        questionText: "What does getUserMedia() return?",
        options: ["User profile data", "A MediaStream containing audio/video tracks from the user's camera and microphone", "DOM elements for camera controls", "A stream of user events"],
        correctAnswer: 1,
        explanation: "navigator.mediaDevices.getUserMedia({ video: true, audio: true }) returns a Promise that resolves to a MediaStream. You can then add its tracks to an RTCPeerConnection or display it in a <video> element.",
        order: 5,
      },
    ],
  },

  // ─────── INFRASTRUCTURE ───────
  {
    slug: "process-management",
    title: "Process Management",
    description: "Keep Node.js apps alive with PM2 — clustering, graceful shutdown, and logs.",
    category: "INFRASTRUCTURE",
    icon: "Activity",
    order: 19,
    difficulty: "INTERMEDIATE",
    questions: [
      {
        questionText: "What is PM2 primarily used for?",
        options: ["Package management", "A Node.js process manager that keeps applications running, handles restarts, clustering, and log management", "A CI/CD tool", "A Docker replacement"],
        correctAnswer: 1,
        explanation: "PM2 (Process Manager 2) manages Node.js processes in production: auto-restarts on crash, cluster mode for multi-core, zero-downtime reloads, log rotation, and startup scripts.",
        order: 1,
      },
      {
        questionText: "What does 'pm2 reload' do vs 'pm2 restart'?",
        options: ["They are identical", "reload performs a zero-downtime graceful restart (new processes start before old ones are killed); restart immediately kills and restarts", "reload is slower but safer for production", "Both cause downtime"],
        correctAnswer: 1,
        explanation: "pm2 reload achieves zero-downtime: new workers start, receive traffic, then old workers drain and exit. pm2 restart kills all processes immediately and restarts — causes a brief downtime.",
        order: 2,
      },
      {
        questionText: "What is PM2 cluster mode?",
        options: ["Connects multiple PM2 instances across servers", "Forks multiple worker processes (one per CPU core) that all share the same port using Node's cluster module", "Clusters log files by date", "A PM2 premium feature"],
        correctAnswer: 1,
        explanation: "exec_mode: 'cluster', instances: 'max' in ecosystem.config.js tells PM2 to fork one worker per CPU core. They all listen on the same port — PM2's load balancer distributes connections.",
        order: 3,
      },
      {
        questionText: "What is graceful shutdown in a Node.js server?",
        options: ["Immediately killing all processes when the server stops", "Handling the SIGTERM signal by stopping new connections, finishing active requests, and then exiting cleanly", "Saving state to disk before exit", "Logging all active connections before shutdown"],
        correctAnswer: 1,
        explanation: "On SIGTERM, a graceful shutdown calls server.close() to stop accepting new connections, waits for in-flight requests to complete, closes DB connections, and then exits. This prevents dropped requests during deployments.",
        order: 4,
      },
      {
        questionText: "What is the purpose of an ecosystem.config.js file in PM2?",
        options: ["A JavaScript ecosystem configuration file", "A declarative PM2 configuration defining app name, script, instances, environment variables, and logging options", "The Node.js ecosystem manifest", "PM2's package.json equivalent"],
        correctAnswer: 1,
        explanation: "ecosystem.config.js is PM2's configuration file. Use 'pm2 start ecosystem.config.js' to start all defined apps. It stores all PM2 settings in version control — much better than manual pm2 start commands.",
        order: 5,
      },
    ],
  },
  {
    slug: "docker",
    title: "Docker",
    description: "Containers, Dockerfiles, multi-stage builds, and Docker Compose.",
    category: "INFRASTRUCTURE",
    icon: "Container",
    order: 20,
    difficulty: "INTERMEDIATE",
    questions: [
      {
        questionText: "What is a Docker container vs a Docker image?",
        options: ["They are the same thing", "An image is a read-only blueprint (template); a container is a running instance of an image", "A container stores data, an image runs code", "Images run on Linux, containers on Windows"],
        correctAnswer: 1,
        explanation: "An image is a static, immutable blueprint containing the app, dependencies, and config. A container is a running, isolated instance created from an image. Multiple containers can run from the same image.",
        order: 1,
      },
      {
        questionText: "What is a multi-stage Docker build?",
        options: ["A build that runs across multiple CI stages", "Using multiple FROM instructions to use one stage for building and a smaller base image for the final artifact — reducing image size", "Building for multiple architectures", "A way to run multiple services in one container"],
        correctAnswer: 1,
        explanation: "Multi-stage builds separate build-time tools from runtime. Stage 1 installs devDependencies and compiles code. Stage 2 starts from a slim base image and copies only the compiled output — dramatically reducing final image size.",
        order: 2,
      },
      {
        questionText: "What is a .dockerignore file?",
        options: ["A file to ignore Docker security warnings", "A file that excludes files/directories from the Docker build context, similar to .gitignore", "A list of Docker commands to skip", "A file to hide Docker images"],
        correctAnswer: 1,
        explanation: ".dockerignore prevents specified files/directories from being sent to the Docker daemon during build. Excluding node_modules, .git, .env, build outputs speeds up builds and prevents accidentally copying secrets.",
        order: 3,
      },
      {
        questionText: "What does 'docker-compose up' do?",
        options: ["Updates Docker to the latest version", "Starts all services defined in docker-compose.yml, creating containers, networks, and volumes as needed", "Uploads images to Docker Hub", "Upgrades running containers"],
        correctAnswer: 1,
        explanation: "docker compose up reads docker-compose.yml, creates the defined network, pulls/builds images, and starts all service containers. Add -d to run in detached (background) mode.",
        order: 4,
      },
      {
        questionText: "What is a Docker volume?",
        options: ["The storage capacity of an image", "A persistent storage mechanism that outlives containers — data written to a volume survives container restarts/deletions", "The compressed size of a Docker layer", "A Docker network segment"],
        correctAnswer: 1,
        explanation: "Volumes decouple data from the container lifecycle. Unlike the container filesystem (lost on deletion), volume data persists. Volumes are used for databases, file uploads, and any data that must survive container restarts.",
        order: 5,
      },
      {
        questionText: "What is the difference between CMD and ENTRYPOINT in a Dockerfile?",
        options: ["They are identical", "ENTRYPOINT sets the main command (harder to override); CMD provides default arguments that can be overridden at runtime", "CMD is for environment variables, ENTRYPOINT for commands", "ENTRYPOINT runs before CMD"],
        correctAnswer: 1,
        explanation: "ENTRYPOINT defines the main executable (e.g., node). CMD provides default arguments (e.g., server.js). When running a container, you can override CMD args but ENTRYPOINT stays fixed unless using --entrypoint flag.",
        order: 6,
      },
    ],
  },
  {
    slug: "aws-ec2",
    title: "AWS EC2",
    description: "Virtual machines in the cloud — instances, security groups, VPC, and Auto Scaling.",
    category: "INFRASTRUCTURE",
    icon: "Cloud",
    order: 21,
    difficulty: "ADVANCED",
    questions: [
      {
        questionText: "What is an EC2 instance type?",
        options: ["The operating system version", "The combination of CPU, memory, storage, and network capacity — e.g., t3.micro, c6i.4xlarge", "The AWS region location", "The billing plan"],
        correctAnswer: 1,
        explanation: "Instance types define hardware specs. t3.micro is cheap with burstable CPU — great for dev. c6i is compute-optimized for CPU-heavy work. r6g is memory-optimized for databases. Choose based on your workload profile.",
        order: 1,
      },
      {
        questionText: "What is an EC2 Security Group?",
        options: ["An IAM user group with EC2 permissions", "A virtual stateful firewall that controls inbound/outbound traffic to EC2 instances at the port and protocol level", "A VPC subnet group", "An SSH key management group"],
        correctAnswer: 1,
        explanation: "Security Groups are stateful firewalls. You define rules: allow port 80/443 from anywhere (0.0.0.0/0), port 22 only from your IP, port 5432 only from app servers. Default is deny all inbound, allow all outbound.",
        order: 2,
      },
      {
        questionText: "What is an AMI (Amazon Machine Image)?",
        options: ["Amazon's machine learning interface", "A pre-configured OS snapshot used to launch EC2 instances — includes OS, installed software, and configuration", "A memory image backup", "An automatic machine inspector"],
        correctAnswer: 1,
        explanation: "An AMI is the template for EC2 instances. AWS provides base AMIs (Amazon Linux, Ubuntu, Windows). You can create custom AMIs from running instances to pre-install your software for faster Auto Scaling.",
        order: 3,
      },
      {
        questionText: "What is an EC2 IAM Role?",
        options: ["A user login for EC2", "Permissions attached to an EC2 instance allowing it to call AWS services (S3, RDS, SSM) without storing credentials", "A role for EC2 pricing", "An SSH role for team access"],
        correctAnswer: 1,
        explanation: "An IAM Role attached to an EC2 instance provides temporary credentials via the EC2 metadata service. Code on the instance can call S3.putObject(), SSM.getParameter() etc. without AWS keys in environment variables.",
        order: 4,
      },
      {
        questionText: "What is the difference between a public and private subnet in a VPC?",
        options: ["Public subnets are faster", "Public subnets have a route to an Internet Gateway (internet-accessible); private subnets have no direct internet route", "Private subnets don't have security groups", "Public subnets are in multiple availability zones"],
        correctAnswer: 1,
        explanation: "Public subnets route traffic through an Internet Gateway — instances can have public IPs and be accessed from the internet. Private subnets only route internally — ideal for databases and backend services. Use NAT Gateway for outbound internet from private subnets.",
        order: 5,
      },
    ],
  },
  {
    slug: "jenkins",
    title: "Jenkins",
    description: "CI/CD automation — pipelines, Jenkinsfile, stages, and deployment workflows.",
    category: "INFRASTRUCTURE",
    icon: "GitMerge",
    order: 22,
    difficulty: "ADVANCED",
    questions: [
      {
        questionText: "What is a Jenkinsfile?",
        options: ["Jenkins configuration file in XML", "A text file (Groovy DSL) that defines the CI/CD pipeline as code, stored in the project's repository", "Jenkins' startup script", "A file listing Jenkins plugins"],
        correctAnswer: 1,
        explanation: "A Jenkinsfile is the pipeline definition as code. Stored in the repo root, it's versioned with the code. Changes to the pipeline are tracked in Git. This is the 'Pipeline as Code' principle.",
        order: 1,
      },
      {
        questionText: "What is the difference between Declarative and Scripted Jenkins pipelines?",
        options: ["They produce different outputs", "Declarative has a structured, opinionated syntax with predefined sections (pipeline, stages, steps); Scripted uses full Groovy programming with more flexibility", "Scripted is deprecated", "Declarative is written in YAML"],
        correctAnswer: 1,
        explanation: "Declarative Pipeline has a strict structure (pipeline{}, stages{}, steps{}) — easier to read and has better syntax validation. Scripted Pipeline is a Groovy script with full flexibility — use when you need complex logic.",
        order: 2,
      },
      {
        questionText: "What is a Jenkins agent?",
        options: ["A Jenkins browser plugin", "The machine/container where pipeline stages actually run — either 'any', a labeled node, or a Docker container", "A monitoring agent for Jenkins health", "An API key for Jenkins"],
        correctAnswer: 1,
        explanation: "Agents define where steps execute. agent any runs on any available node. agent { docker 'node:20' } runs in a Docker container. Labeled agents route to specific machines (Linux, Windows, high-memory).",
        order: 3,
      },
      {
        questionText: "What does a 'post' block do in a Declarative Jenkins pipeline?",
        options: ["Sends POST HTTP requests", "Defines actions to run after the pipeline or stage completes — always, success, failure, unstable", "Posts build status to a dashboard", "Defines post-build artifacts"],
        correctAnswer: 1,
        explanation: "The post block runs after stages complete. 'always' runs regardless of result. 'success' and 'failure' run conditionally. Common uses: send Slack notifications on failure, publish test reports, clean up Docker images.",
        order: 4,
      },
      {
        questionText: "How do you run two stages in parallel in a Jenkins Declarative Pipeline?",
        options: ["Use 'concurrent: true' on each stage", "Nest stages inside a 'parallel' block within a stage", "Use the @Parallel annotation", "Run two separate pipelines simultaneously"],
        correctAnswer: 1,
        explanation: "stage('Test') { parallel { stage('Unit Tests') {...} stage('Integration Tests') {...} } } runs both nested stages simultaneously, reducing pipeline duration.",
        order: 5,
      },
    ],
  },

  // ─────── CLOUD & DEVOPS ───────
  {
    slug: "kubernetes",
    title: "Kubernetes",
    description: "Container orchestration — Pods, Deployments, Services, Ingress, and scaling.",
    category: "CLOUD_DEVOPS",
    icon: "Hexagon",
    order: 23,
    difficulty: "ADVANCED",
    questions: [
      {
        questionText: "What is a Kubernetes Pod?",
        options: ["A type of Kubernetes cluster", "The smallest deployable unit — one or more containers sharing network namespace, storage, and lifecycle", "A Kubernetes worker node", "A virtual machine in Kubernetes"],
        correctAnswer: 1,
        explanation: "A Pod wraps one or more tightly coupled containers that share the same IP, hostname, and volumes. Containers in a Pod communicate via localhost. Pods are ephemeral — you manage them through Deployments.",
        order: 1,
      },
      {
        questionText: "What problem does a Kubernetes Deployment solve?",
        options: ["Network routing in the cluster", "Manages the desired state of Pods — ensures N replicas run, handles rolling updates, and automatically restarts failed Pods", "Storage management for containers", "Authentication and authorization"],
        correctAnswer: 1,
        explanation: "A Deployment declares desired state (e.g., 3 replicas of my-app:v2). The Deployment Controller continuously reconciles actual vs desired state, replacing failed Pods and performing rolling updates with zero downtime.",
        order: 2,
      },
      {
        questionText: "What is a Kubernetes Service?",
        options: ["A microservice in Kubernetes", "A stable DNS name and IP that load-balances traffic to a set of Pods, surviving Pod replacements", "A background job runner", "An API gateway for the cluster"],
        correctAnswer: 1,
        explanation: "Services provide a stable endpoint for a dynamic set of Pods (selected by labels). Even as Pods restart and get new IPs, the Service IP/DNS stays the same. Types: ClusterIP (internal), NodePort, LoadBalancer.",
        order: 3,
      },
      {
        questionText: "What does 'kubectl apply -f deployment.yaml' do?",
        options: ["Deletes the deployment", "Applies the desired state from the YAML file — creates if new, updates if existing", "Validates the YAML syntax", "Applies CPU and memory limits"],
        correctAnswer: 1,
        explanation: "kubectl apply is declarative — it tells Kubernetes 'this is the desired state'. Kubernetes computes the diff from current state and makes the minimal changes needed. Use 'apply' over 'create' for idempotent deployments.",
        order: 4,
      },
      {
        questionText: "What is a Kubernetes Ingress?",
        options: ["Network traffic entering a Pod", "An API object that manages HTTP/HTTPS routing from outside the cluster to Services — hostname/path-based routing with TLS", "A type of storage volume", "Cluster authentication rules"],
        correctAnswer: 1,
        explanation: "Ingress routes external HTTP/HTTPS traffic to internal Services based on host (api.example.com) or path (/api vs /app). The Ingress Controller (nginx, traefik) implements the routing rules.",
        order: 5,
      },
      {
        questionText: "What is a Kubernetes ConfigMap?",
        options: ["A map of container configurations", "A Kubernetes object storing non-sensitive configuration as key-value pairs, injected into Pods as env vars or files", "A network configuration map", "A Helm chart configuration"],
        correctAnswer: 1,
        explanation: "ConfigMaps store non-sensitive config (feature flags, API URLs, config files). They're separate from the container image, making apps portable. For secrets (passwords, API keys), use Kubernetes Secrets instead.",
        order: 6,
      },
    ],
  },
  {
    slug: "devops",
    title: "DevOps for Developers",
    description: "CI/CD, IaC, GitOps, observability, and the DevOps culture and toolchain.",
    category: "CLOUD_DEVOPS",
    icon: "Rocket",
    order: 24,
    difficulty: "ADVANCED",
    questions: [
      {
        questionText: "What is Continuous Integration (CI)?",
        options: ["Deploying to production continuously", "Automatically building and testing code every time a developer pushes to the repository", "Integrating third-party services", "A way to continuously monitor infrastructure"],
        correctAnswer: 1,
        explanation: "CI is the practice of automatically building and running tests on every code commit. It provides fast feedback — developers know within minutes if their change broke something, preventing integration hell.",
        order: 1,
      },
      {
        questionText: "What is Infrastructure as Code (IaC)?",
        options: ["Writing JavaScript for cloud infrastructure", "Managing and provisioning infrastructure through machine-readable definition files (Terraform, CloudFormation) instead of manual processes", "Code that runs on infrastructure", "Automated testing of infrastructure"],
        correctAnswer: 1,
        explanation: "IaC means your AWS VPCs, EC2 instances, and databases are defined in Terraform/CloudFormation files committed to Git. Infrastructure becomes reproducible, reviewable, and version-controlled like application code.",
        order: 2,
      },
      {
        questionText: "What is GitOps?",
        options: ["Using Git for code collaboration", "A practice where the Git repository is the single source of truth for deployments — changes are applied automatically when code is merged", "GitHub's operations team", "Operations scripts stored in Git"],
        correctAnswer: 1,
        explanation: "GitOps uses Git as the source of truth for infrastructure and deployment state. Tools like ArgoCD or Flux watch the Git repo and automatically sync the cluster state to match. Rollbacks are git reverts.",
        order: 3,
      },
      {
        questionText: "What are the 'three pillars' of observability?",
        options: ["Performance, Uptime, Reliability", "Logs, Metrics, and Traces", "CPU, Memory, and Network", "Monitoring, Alerting, and Dashboards"],
        correctAnswer: 1,
        explanation: "Observability has three pillars: Logs (discrete events — what happened), Metrics (numeric measurements over time — how the system performs), Traces (distributed request flows — where time was spent across services).",
        order: 4,
      },
      {
        questionText: "What is a Blue/Green deployment?",
        options: ["Deploying to blue and green environments simultaneously", "Running two identical production environments — traffic shifts from blue (current) to green (new) atomically, enabling instant rollback", "A color-coded deployment rating system", "A testing strategy using color-coded branches"],
        correctAnswer: 1,
        explanation: "Blue/Green maintains two identical production environments. New version deploys to green while blue serves traffic. After testing, traffic switches to green. Rollback = switch back to blue. Zero downtime, instant rollback.",
        order: 5,
      },
      {
        questionText: "What is an SLO (Service Level Objective)?",
        options: ["A legal service agreement", "A target value for service reliability (e.g., 99.9% uptime) measured by SLIs — used to balance reliability vs feature velocity", "A software license obligation", "A server load optimization metric"],
        correctAnswer: 1,
        explanation: "SLOs define reliability targets. SLI (indicator) measures actual behavior (availability). SLO is the target (99.9%). SLA is the contract with penalties. Error budgets (100% - SLO) quantify how much reliability can be 'spent' on risky changes.",
        order: 6,
      },
    ],
  },
]

async function main() {
  console.log("🌱 Starting seed...")

  for (const topic of topics) {
    const { questions, ...topicData } = topic

    const upsertedTopic = await prisma.topic.upsert({
      where: { slug: topicData.slug },
      update: topicData,
      create: topicData,
    })

    // Delete existing questions to re-seed cleanly
    await prisma.question.deleteMany({ where: { topicId: upsertedTopic.id } })

    await prisma.question.createMany({
      data: questions.map((q) => ({
        ...q,
        topicId: upsertedTopic.id,
      })),
    })

    console.log(`  ✓ ${topicData.title} (${questions.length} questions)`)
  }

  const topicCount = await prisma.topic.count()
  const questionCount = await prisma.question.count()
  console.log(`\n✅ Seed complete: ${topicCount} topics, ${questionCount} questions`)
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
